version: "3.8"

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    entrypoint: ["sh", "/usr/src/app/entrypoint.sh"]
    volumes:
      - "./back:/usr/src/app"
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - SECRET_KEY=secret
    networks:
      - app-network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - "./front:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
